#!/usr/bin/env python3
"""
Stage 01: 生成 Mini-Agent 配置文件（DashScope 版）
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import shutil
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from common import configure_stdio, normalize_model, read_settings


def build_config_yaml(api_key: str, base_url: str, model: str) -> str:
    """生成 config.yaml 文本。"""
    # 注意：mini-agent 会根据 provider 处理 OpenAI 协议，因此此处固定 provider=openai
    return f"""# Auto-generated by mini_agent_dashscope/stage01
api_key: "{api_key}"
api_base: "{base_url}"
model: "{model}"
provider: "openai"

retry:
  enabled: true
  max_retries: 3
  initial_delay: 1.0
  max_delay: 60.0
  exponential_base: 2.0

max_steps: 60
workspace_dir: "./workspace"
system_prompt_path: "system_prompt.md"

tools:
  enable_file_tools: true
  enable_bash: true
  enable_note: true
  enable_skills: true
  skills_dir: "./skills"
  enable_mcp: true
  mcp_config_path: "mcp.json"
  mcp:
    connect_timeout: 10.0
    execute_timeout: 60.0
    sse_read_timeout: 120.0
"""


def build_system_prompt() -> str:
    return """You are Mini-Agent running with DashScope.

Rules:
1) Prefer read/edit tools over destructive shell operations.
2) Confirm intent before risky commands.
3) Keep responses concise and actionable.
4) If information may be outdated, propose web search with tools.
"""


def build_mcp_json() -> str:
    # 默认全部 disabled，用户按需开启。
    payload = {
        "mcpServers": {
            "minimax_search": {
                "description": "MiniMax Search",
                "type": "stdio",
                "command": "uvx",
                "args": [
                    "--from",
                    "git+https://github.com/MiniMax-AI/minimax_search",
                    "minimax-search",
                ],
                "env": {
                    "JINA_API_KEY": "",
                    "SERPER_API_KEY": "",
                    "MINIMAX_API_KEY": "",
                },
                "disabled": True,
            }
        }
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def backup_if_exists(path: Path) -> None:
    if not path.exists():
        return
    stamp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = path.with_suffix(path.suffix + f".bak.{stamp}")
    shutil.copy2(path, backup_path)
    print(f"已备份: {backup_path}")


def main() -> int:
    parser = argparse.ArgumentParser(description="生成 Mini-Agent DashScope 配置")
    parser.add_argument("--overwrite", action="store_true", help="存在文件时直接覆盖（仍会先备份）")
    args = parser.parse_args()

    configure_stdio()
    settings = read_settings()
    if not settings.api_key:
        print("未检测到 API Key。请先设置 OPENAI_API_KEY 或 DASHSCOPE_API_KEY。")
        return 1

    # 对 mini-agent 推荐使用 /v1 根路径写法；内部会补齐 endpoints。
    mini_agent_base = settings.base_url.replace("/chat/completions", "")
    model = normalize_model(settings.model)

    config_dir = Path.home() / ".mini-agent" / "config"
    config_dir.mkdir(parents=True, exist_ok=True)

    config_path = config_dir / "config.yaml"
    mcp_path = config_dir / "mcp.json"
    prompt_path = config_dir / "system_prompt.md"

    if config_path.exists() and not args.overwrite:
        print(f"配置已存在: {config_path}")
        print("如需覆盖请加参数: --overwrite")
        return 0

    backup_if_exists(config_path)
    backup_if_exists(mcp_path)
    backup_if_exists(prompt_path)

    config_path.write_text(
        build_config_yaml(settings.api_key, mini_agent_base, model),
        encoding="utf-8",
    )
    mcp_path.write_text(build_mcp_json(), encoding="utf-8")
    prompt_path.write_text(build_system_prompt(), encoding="utf-8")

    print("=== mini_agent_dashscope Stage 01: 配置生成完成 ===")
    print(f"config: {config_path}")
    print(f"mcp:    {mcp_path}")
    print(f"prompt: {prompt_path}")
    print(f"model:  {model}")
    print(f"base:   {mini_agent_base}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
